
name: Build LaTeX document
on: 
  push:
    branches: 
      - master
  pull_request_target:
    branches: 
      - master
  

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install fonts
        run: |
          sudo apt-get install -y fonts-nakula fonts-liberation
      - name: Copy fonts
        run: |
          mkdir -p ~/.local/share/fonts && cp -r fonts/* ~/.local/share/fonts/
      - name: Update font cache
        run:  fc-cache -rv
      - name: xelatex iith logo
        uses: dante-ev/latex-action@latest
        with:
          root_file: iith-lh.tex
          compiler: xelatex
          args: -interaction=nonstopmode -shell-escape
      - name: xelatex iith lh everypge
        uses: dante-ev/latex-action@latest
        with:
          root_file: iith-lh-eveypage.tex
          compiler: xelatex
          args: -interaction=nonstopmode -shell-escape
